const products = [
    {
        id: "rec43w3ipXvP28vog",
        title: "high-back bench",
        company: "ikea",
        url: "images/1.jpeg",
        price: 9.99,
    },
    {
        id: "rec4f2RIftFCb7aHh",
        title: "albany TABLE",
        company: "marcos",
        url: "images/2.jpeg",
        price: 79.99,
    },
    {
        id: "rec8kkCmSiMkbkiko",
        title: "accent chair",
        company: "caressa",
        url: "images/3.jpeg",
        price: 25.99,
    },
    {
        id: "recBohCqQsot4Q4II",
        title: "wooden table",
        company: "caressa",
        url: "images/4.jpg",
        price: 45.99,
    },
    {
        id: "recDG1JRZnbpRHpoy",
        title: "dining table",
        company: "caressa",
        url: "images/5.jpg",
        price: 6.99,
    },
    {
        id: "recNWGyP7kjFhSqw3",
        title: "sofa set",
        company: "liddy",
        url: "images/6.jpeg",
        price: 69.99,
    },
    {
        id: "recZEougL5bbY4AEx",
        title: "modern bookshelf",
        company: "marcos",
        url: "images/7.jpg",
        price: 8.99,
    },
    {
        id: "recjMK1jgTb2ld7sv",
        title: "emperor bed",
        company: "liddy",
        url: "images/8.jpg",
        price: 21.99,
    },
    {
        id: "recmg2a1ctaEJNZhu",
        title: "utopia sofa",
        company: "marcos",
        url: "images/9.jpg",
        price: 39.95,
    },
    {
        id: "recvKMNR3YFw0bEt3",
        title: "entertainment center",
        company: "liddy",
        url: "images/10.jpg",
        price: 29.98,
    },
    {
        id: "recxaXFy5IW539sgM",
        title: "albany sectional",
        company: "ikea",
        url: "images/11.jpeg",
        price: 10.99,
    },
    {
        id: "recyqtRglGNGtO4Q5",
        title: "leather sofa",
        company: "liddy",
        url: "images/12.jpg",
        price: 9.99,
    },
];
